language: cpp
dist: xenial
matrix:
  include:
    - name: "clang (Linux)"
      os: linux
      compiler: clang
    - name: "gcc (Linux)"
      os: linux
      compiler: gcc
    - name: "clang (macOS)"
      os: osx
      compiler: clang
    - name: "MSVC (Windows)"
      os: windows
      # CMake picks up MSVC regardless of what compiler we specify here.
install:
  # Add Linux headers needed to build kernel module.
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get install -y "linux-headers-$(uname -r)";
    fi
script:
  # It would be a bit nicer to use `cmake -B build .`, but `-B` isn't
  # supported on older CMake.
  - mkdir build
  - cd build
  - cmake ..
  # Invoke build in platform+generator agnostic way
  - cmake --build .
