language: cpp
dist: bionic
matrix:
  include:
    - name: "Linux / gcc / x86_64, i686"
      os: linux
      compiler: gcc
before_script:
  - ./ci/show-cpu-info
  - "curl -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/cpu-platform"
  - "curl -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/machine-type"
script:
  - ./ci/vm/run
